# Stage 1: Build
FROM node:22-alpine AS build-stage
WORKDIR /app

# Add build arguments
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN yarn build

# Stage 2: Serve
FROM nginx:alpine
# Copy build result to nginx
COPY --from=build-stage /app/dist /usr/share/nginx/html
# Copy custom nginx config if needed or use default
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
